/*
 * Drug data, transcribed from "Paramedic Pharmacology – TN Protocols"
 * (D. Weaver, rev. 08/15/2025). Wording follows the slides; only spacing,
 * capitalization and obvious typos were cleaned up.
 *
 * Core (tested) fields: name, indications, contraindications, adult, peds.
 * Everything else is secondary reference info.
 *
 * Each list is one item per array entry. An empty list means the deck
 * doesn't give that info; quizzes skip it.
 *
 * label = standard syringe-label color family (ASTM D4774), shown as a tag.
 * groups = study sets used by the drug picker.
 */
window.DRUGS = [
  {
    id: 'acetaminophen',
    name: 'Acetaminophen',
    aliases: ['tylenol', 'apap'],
    trade: ['Tylenol'],
    groups: ['pain'],
    label: 'other',
    therapeutic: 'Analgesic; antipyretic',
    pharmacological: 'Nervous system disruptor',
    indications: ['Fever', 'Pain'],
    contraindications: ['Liver disease (cannot process it)'],
    cautions: [],
    adult: ['1000 mg PO'],
    peds: ['>3 months: 15 mg/kg PO'],
    moa: 'Blocks pain receptors; inhibits prostaglandin synthesis that controls temperature regulation in the CNS.',
    adverse: ['Dizziness', 'Lethargy', 'Nausea', 'Abdominal pain'],
    protocolsTN: ['Fever control'],
    protocolsNASEMSO: ['Minor pain', 'Febrile seizure', 'Shock (sepsis)'],
    mnemonic: '',
    notes: ['Overdose is treated with Mucomyst.']
  },
  {
    id: 'adenosine',
    name: 'Adenosine',
    aliases: ['adenocard'],
    trade: ['Adenocard'],
    groups: ['cardiac'],
    label: 'other',
    therapeutic: 'Antidysrhythmic',
    pharmacological: 'Not readily known',
    indications: ['Narrow complex tachycardia', 'SVT'],
    contraindications: ['Second or third-degree heart block'],
    cautions: ['Sick sinus syndrome (pacemaker does not work properly and causes abnormal beats)'],
    adult: ['6 mg (AHA initial dose)', '12 mg (TN initial dose)', '12 mg follow-up dose'],
    peds: ['0.1 mg/kg (max 6 mg)', '0.2 mg/kg (max 12 mg) second dose'],
    moa: 'Chemical cardioversion: decreases automaticity in the SA node and slows conduction in the SA and AV nodes.',
    adverse: ['Asystole', 'Nausea', 'Hypotension', 'Chest pain', 'Bradycardia', 'Lightheadedness'],
    protocolsTN: ['Supraventricular tachycardia (SVT)', 'V-tach with a pulse'],
    protocolsNASEMSO: ['Tachycardia with a pulse', 'Regular wide complex tachycardia (stable)'],
    mnemonic: 'aDenosine: D for Drops heart rate. adenoSine: S for Slows heart rate.',
    notes: ['The slide lists trade and generic swapped. Generic = adenosine, trade = Adenocard.']
  },
  {
    id: 'albuterol',
    name: 'Albuterol',
    aliases: ['proventil', 'ventolin'],
    trade: ['Proventil'],
    groups: ['resp'],
    label: 'other',
    therapeutic: 'Bronchodilator',
    pharmacological: 'Beta-2 agonist',
    indications: ['Respiratory distress'],
    contraindications: ['Symptomatic tachydysrhythmias (above 150 bpm)'],
    cautions: [],
    adult: ['2.5 mg in 3 mL q5 min if heart rate is less than 150'],
    peds: ['2.5 mg in 3 mL q5 min if heart rate is less than 200'],
    moa: 'Beta-2 agonist; relaxes bronchial smooth muscle.',
    adverse: ['Tachycardia', 'Palpitations'],
    protocolsTN: ['Respiratory distress', 'Pulmonary edema', 'Anaphylactic shock', 'Chlorine exposure (airway irritant)', 'Crush injury (albuterol drives potassium into cells)', 'Hyperglycemia with hyperkalemia'],
    protocolsNASEMSO: ['Respiratory distress', 'Pulmonary edema', 'Anaphylactic shock', 'Chlorine exposure (airway irritant)', 'Crush injury (albuterol drives potassium into cells)', 'Hyperglycemia with hyperkalemia'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'amiodarone',
    name: 'Amiodarone',
    aliases: ['amio', 'cordarone', 'pacerone', 'nexterone'],
    trade: ['Pacerone', 'Cordarone', 'Nexterone'],
    groups: ['cardiac'],
    label: 'other',
    therapeutic: 'Antidysrhythmic',
    pharmacological: 'Potassium channel blocker',
    indications: ['Wide complex tachycardia', 'V-fib', 'Pulseless V-tach', 'Symptomatic PVCs'],
    contraindications: ['Second or third-degree heart block', 'Bradycardia with PVCs'],
    cautions: ['Sick sinus syndrome', 'Cardiogenic shock'],
    adult: ['V-fib / pulseless V-tach: 300 mg', 'Followed by 150 mg (total of 450 mg)', 'V-tach with a pulse: 150 mg over 2 min or drip'],
    peds: ['5 mg/kg (repeat for a total of 15 mg/kg)'],
    moa: 'Affects sodium, potassium, and calcium; prolongs action potential and repolarization; decreases AV conduction and sinus node function; relaxes smooth muscle, causing vasodilation.',
    adverse: ['Headache', 'Dizziness', 'Hypotension', 'Muscle weakness', 'Cardiogenic shock', 'Nausea', 'Vomiting'],
    protocolsTN: ['Acute coronary syndrome / STEMI (PVC treatment)', 'Premature ventricular complexes', "Torsade de pointes", 'Ventricular fibrillation / pulseless V-tach', 'V-tach with a pulse', 'Post resuscitation'],
    protocolsNASEMSO: ['Tachycardia with a pulse (wide regular complex)', 'Cardiac arrest'],
    mnemonic: 'AMiodarone: AMmo for the heart. amiOdarone: Oh crap.',
    notes: []
  },
  {
    id: 'aspirin',
    name: 'Aspirin',
    aliases: ['asa', 'bayer', 'acetylsalicylic acid'],
    trade: ['Bayer', 'ASA (acetylsalicylic acid)'],
    groups: ['cardiac', 'pain'],
    label: 'other',
    therapeutic: 'Antiplatelet aggregate',
    pharmacological: 'NSAID; slight vasodilation',
    indications: ['ACS', 'Mild pain', 'Fever'],
    contraindications: ['GI bleeding', 'Ulcers', 'Hemorrhagic stroke'],
    cautions: ['Bleeding disorders'],
    adult: ['324 mg'],
    peds: ["N/A: risk of Reye's syndrome (swelling of the liver and brain; potentially fatal)"],
    moa: 'Inhibits synthesis of prostaglandin and inhibits platelet aggregation.',
    adverse: ['Nausea', 'Vomiting', 'Heartburn'],
    protocolsTN: ['Chest pain'],
    protocolsNASEMSO: ['Chest pain'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'atropine',
    name: 'Atropine Sulfate',
    aliases: ['atropine'],
    trade: ['Atropine'],
    groups: ['cardiac', 'tox'],
    label: 'anticholinergic',
    therapeutic: 'Parasympatholytic / anticholinergic',
    pharmacological: 'Bronchodilator; antidysrhythmic',
    indications: ['Bradycardia', 'Asthma', 'COPD', 'Organophosphate poisoning', 'RSI premedication (peds)'],
    contraindications: ['2nd and 3rd degree heart blocks'],
    cautions: ['AMI (increases O2 demand)', 'Cardiac transplant (does not carry pacemakers)', 'Neonates (increased sensitivity to anticholinergic effects; risk of paradoxical bradycardia)'],
    adult: ['0.5–1 mg IV, repeat q3–5 min (max dose 0.04 mg/kg)', 'Organophosphates, elderly: 1.0 mg IM'],
    peds: ['0.02 mg/kg (max dose 0.04 mg/kg)', 'RSI: 0.01–0.02 mg/kg (max 0.5 mg)', 'Organophosphates, infant: 0.5 mg IM or 0.02 mg/kg IV', 'Organophosphates, child 2–10: 1.0 mg IM', 'Organophosphates, adolescent: 2.0 mg IM/IV'],
    moa: 'Blocks cholinergic receptors, increasing chronotropy and dromotropy (conduction through the AV node), reducing respiratory secretions and causing bronchodilation.',
    adverse: ['Tachycardia', 'Hypertension', 'Palpitations', 'Confusion', 'Dilated pupils', 'Blurred vision', 'Dry mouth', 'Flushed skin', 'Headache'],
    protocolsTN: ['Symptomatic bradycardia', 'Nerve agent exposure', 'Organophosphates'],
    protocolsNASEMSO: ['Bradycardia', 'Acetylcholinesterase inhibitor exposure (carbamates, nerve agents, organophosphates)', 'Beta blocker poisoning / overdose', 'Calcium channel blocker OD (0.1 mg/kg, max 1 mg)'],
    mnemonic: 'atROPine = jump ROPe, increases HR.',
    notes: ['Inotropic = contractile strength. Chronotropic = heart rate. Dromotropic = conduction speed, especially through the AV node.']
  },
  {
    id: 'calcium-chloride',
    name: 'Calcium Chloride',
    aliases: ['cacl', 'cacl2', 'calcium'],
    trade: ['Kalcinate'],
    groups: ['tox'],
    label: 'other',
    therapeutic: 'Antidote',
    pharmacological: 'Electrolyte',
    indications: ['Hydrofluoric acid burns (slurry to stop burns)', 'Calcium channel blocker overdose', 'Hypocalcemia', 'Hypermagnesemia', 'Hyperkalemia'],
    contraindications: ['Hypercalcemia', 'Digitalis toxicity', 'V-fib'],
    cautions: [],
    adult: ['500 mg'],
    peds: ['20 mg/kg (0.2 mL/kg)'],
    moa: 'Competes with potassium ions at cardiac and neuromuscular receptor sites to increase inotropy and ventricular automaticity and restore myocardial conduction in the presence of hyperkalemia.',
    adverse: ['Bradycardia', 'Hypotension', 'Acidosis'],
    protocolsTN: ['Crush syndrome'],
    protocolsNASEMSO: ['Hyperglycemia with hyperkalemia', 'Cardiac arrest of dialysis patient', 'Treatment of magnesium toxicity', 'Treatment of crush injuries', 'Hydrofluoric acid burns', 'Calcium channel blocker OD'],
    mnemonic: '',
    notes: ['Three times more calcium than calcium gluconate.', 'Do not mix with sodium bicarbonate.']
  },
  {
    id: 'calcium-gluconate',
    name: 'Calcium Gluconate',
    aliases: ['gluconate', 'calcium'],
    trade: ['Kalcinate'],
    groups: ['tox'],
    label: 'other',
    therapeutic: 'Antidote',
    pharmacological: 'Electrolyte',
    indications: ['Hydrofluoric acid burns', 'Calcium channel blocker overdose', 'Hypocalcemia', 'Hypermagnesemia', 'Hyperkalemia'],
    contraindications: [],
    cautions: [],
    adult: ['1–2 g'],
    peds: ['60 mg/kg (0.6 mL/kg)'],
    moa: '',
    adverse: [],
    protocolsTN: ['Crush syndrome'],
    protocolsNASEMSO: ['Hyperglycemia with hyperkalemia', 'Cardiac arrest of dialysis patient', 'Treatment of magnesium toxicity', 'Treatment of crush injuries', 'Hydrofluoric acid burns', 'Calcium channel blocker OD'],
    mnemonic: '',
    notes: ['The deck gives no separate contraindications for gluconate; see Calcium Chloride (hypercalcemia, digitalis toxicity, V-fib).']
  },
  {
    id: 'dextrose',
    name: 'Dextrose',
    aliases: ['d50', 'd25', 'd10', 'glucose', 'dextrose 50%'],
    trade: [],
    groups: ['tox'],
    label: 'other',
    therapeutic: 'Carbohydrate',
    pharmacological: '',
    indications: ['Hypoglycemia'],
    contraindications: ['Intracranial bleed'],
    cautions: [],
    adult: ['12.5–25 g IVP (D50)'],
    peds: ['2 mL/kg (D25)', '250 cc bag of D10'],
    moa: 'Provides simple sugar to raise glucose level.',
    adverse: ['Necrotic in veins (tissue necrosis if it infiltrates)'],
    protocolsTN: ['Hypoglycemia', 'Crush injury (insulin administration)'],
    protocolsNASEMSO: ['Hypoglycemia'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'diazepam',
    name: 'Diazepam',
    aliases: ['valium'],
    trade: ['Valium'],
    groups: ['pain'],
    label: 'benzo',
    therapeutic: 'Benzodiazepine',
    pharmacological: 'Anticonvulsant',
    indications: ['Seizure', 'Sedation'],
    contraindications: ['Respiratory depression', 'Altered LOC', 'Hypotension'],
    cautions: [],
    adult: ['2–10 mg slow IVP, titrate to effect'],
    peds: ['0.1 mg/kg slow IVP'],
    moa: 'Acts on the postsynaptic effects of GABA transmission, resulting in presynaptic inhibition.',
    adverse: ['Respiratory depression', 'Hypotension', 'Bradycardia'],
    protocolsTN: ['Preeclampsia and eclampsia', 'Supraventricular tachycardia (sedation for most cardioversions)', 'Drug ingestion (seizure)', 'Nerve agent exposure', 'Snakebite', 'Seizure'],
    protocolsNASEMSO: ['Combative patient', 'End of life care', 'Seizures', 'Acetylcholinesterase exposure', 'Hyperthermia'],
    mnemonic: '',
    notes: ['Use flumazenil (Romazicon) to reverse overdose.']
  },
  {
    id: 'dopamine',
    name: 'Dopamine',
    aliases: ['intropin'],
    trade: ['Intropin'],
    groups: ['cardiac'],
    label: 'vasopressor',
    therapeutic: 'Antidysrhythmic; vasopressor',
    pharmacological: 'Positive inotrope',
    indications: ['Hypotension', 'Cardiogenic shock', 'CHF'],
    contraindications: ['Hypotension without prior fluid resuscitation'],
    cautions: ['AMI (increases heart rate and affects preload)'],
    adult: ['2–20 mcg/kg/min'],
    peds: ['2–20 mcg/kg/min'],
    moa: 'Acts on alpha and beta receptors to increase inotropy, dromotropy, and chronotropy.',
    adverse: ['Headache', 'Palpitations', 'Hypertension', 'Tachycardia'],
    protocolsTN: [],
    protocolsNASEMSO: ['Bradycardia (high heart block)', 'Shock'],
    mnemonic: '',
    notes: ['Not currently recommended in TN EMS.', 'Inotropic = contractile strength. Chronotropic = heart rate. Dromotropic = conduction speed, especially through the AV node.']
  },
  {
    id: 'diphenhydramine',
    name: 'Diphenhydramine',
    aliases: ['benadryl'],
    trade: ['Benadryl'],
    groups: ['resp'],
    label: 'other',
    therapeutic: 'H1 antihistamine',
    pharmacological: 'Histamine blocker',
    indications: ['Allergic reactions', 'Anaphylaxis', 'Nausea (off-label)'],
    contraindications: ['MAO inhibitors (early antidepressants) potentiate the effect'],
    cautions: ['Neonates and infants (not a sleep aid)'],
    adult: ['25–50 mg IM / slow IVP'],
    peds: ['1 mg/kg'],
    moa: 'Blocks histamine at H1 receptor sites; reverses dystonic reactions and extrapyramidal symptoms.',
    adverse: ['Dizziness', 'Drowsiness', 'Tachycardia'],
    protocolsTN: ['Anaphylactic shock', 'Chemical restraint'],
    protocolsNASEMSO: ['Nausea and vomiting'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'epi-10000',
    name: 'Epinephrine 1:10,000',
    aliases: ['epinephrine', 'epi', 'adrenalin', 'epi 1:10000', 'epi 1:10,000', 'epinephrine 1:10000', 'cardiac epi', 'epinephrine 0.1 mg/ml'],
    trade: ['Adrenalin'],
    concentration: '0.1 mg/mL',
    groups: ['cardiac'],
    label: 'vasopressor',
    therapeutic: 'Antidysrhythmic',
    pharmacological: 'Alpha/beta adrenergic agonist',
    indications: ['Cardiac arrest', 'Push dose pressor'],
    contraindications: ['Hypersensitivity', 'Cardiac dilatation', 'Coronary insufficiency (no preload or volume; AMI)'],
    cautions: [],
    adult: ['Cardiac arrest: 0.5–1 mg (max dose 3 mg; higher totals linked to poor neurological outcome)', 'Push dose pressor: 2–10 mcg/min', 'Push dose pressor (10 mcg/mL mix): 5–10 mcg (0.5–1 mL) slow IV push over 30–60 sec every 2–5 min'],
    peds: ['Cardiac arrest: 0.01 mg/kg IV/IO q5 min'],
    moa: 'Increases cardiac output and heart rate; vasoconstriction; bronchial smooth muscle relaxation.',
    adverse: ['Tachycardia', 'Hypertension'],
    protocolsTN: ['Symptomatic bradycardia', 'Pulseless electrical activity (PEA)', 'Ventricular asystole', 'V-fib / V-tach', 'Post resuscitation', 'Hypovolemic shock', 'Neurogenic shock', 'Septic shock', 'Spinal cord injury', 'Trauma, blunt', 'Trauma, penetrating', 'Neonatal resuscitation'],
    protocolsNASEMSO: ['Bradycardia (0.02–0.2 mcg/kg/min; 10–20 mcg push dose)', 'Shock (second line, 0.05–0.3 mcg/kg/min)', 'Cardiac arrest', 'Neonatal resuscitation'],
    mnemonic: 'EPI = Every Pulseless Individual.',
    notes: ['First-line pressor choice in TN.', 'Making push-dose epi (10 mcg/mL): draw 9 mL NS into a 10 mL syringe, then draw in 1 mL of epinephrine 0.1 mg/mL (1 mg/10 mL, 1:10,000). Label the syringe.']
  },
  {
    id: 'epi-1000',
    name: 'Epinephrine 1:1,000',
    aliases: ['epinephrine', 'epi', 'epipen', 'epi pen', 'adrenalin', 'epi 1:1000', 'epi 1:1,000', 'epinephrine 1:1000', 'epinephrine 1 mg/ml'],
    trade: ['EpiPen', 'Adrenalin'],
    concentration: '1 mg/mL',
    groups: ['resp'],
    label: 'vasopressor',
    therapeutic: 'Antidysrhythmic',
    pharmacological: 'Alpha/beta adrenergic agonist',
    indications: ['Allergic reactions', 'Anaphylaxis', 'Croup (peds, nebulized)'],
    contraindications: ['Hypersensitivity', 'Cardiac dilatation', 'Coronary insufficiency (no preload or volume; AMI)'],
    cautions: [],
    adult: ['Anaphylaxis: 0.3–0.5 mg'],
    peds: ['Anaphylaxis: 0.01 mg/kg IM q5 min (max 0.3 mg)', 'Croup: 1 mg in 2.5–3 mL saline nebulized (not true racemic epi)'],
    moa: 'Increases cardiac output and heart rate; vasoconstriction; bronchial smooth muscle relaxation.',
    adverse: ['Tachycardia', 'Hypertension'],
    protocolsTN: ['Anaphylactic shock', 'Croup', 'Respiratory distress (asthma/COPD)'],
    protocolsNASEMSO: ['Anaphylaxis and allergic reaction (adult 0.3 mg IM; peds 0.15 mg IM; nebulized 1 mg/mL in 5 mL)', 'Pediatric respiratory distress (1 mg in 5 mL saline)', 'Croup'],
    mnemonic: 'EPI = Every Pulseless Individual.',
    notes: []
  },
  {
    id: 'fentanyl',
    name: 'Fentanyl',
    aliases: ['sublimaze', 'sublimize'],
    trade: ['Sublimaze'],
    groups: ['pain'],
    label: 'opioid',
    therapeutic: 'Analgesic',
    pharmacological: 'Synthetic narcotic analgesic',
    indications: ['Pain', 'Sedation'],
    contraindications: ['Head injury', 'Myasthenia gravis (may cause muscle rigidity)'],
    cautions: [],
    adult: ['1–2 mcg/kg (50–100 mcg)'],
    peds: ['0.5–2 mcg/kg'],
    moa: 'Increases pain threshold; binds to opioid pain receptor sites.',
    adverse: ['Nausea', 'Vomiting', 'Bradycardia', 'Hypotension'],
    protocolsTN: ['Pediatric pain control (intranasal)', 'Pain control (first line)', 'Post-intubation sedation'],
    protocolsNASEMSO: ['Pain management'],
    mnemonic: '',
    notes: ['Myasthenia gravis: chronic autoimmune disease causing weakness in the voluntary muscles.']
  },
  {
    id: 'glucagon',
    name: 'Glucagon',
    aliases: ['glucagen'],
    trade: ['GlucaGen'],
    groups: ['tox'],
    label: 'other',
    therapeutic: 'Antihypoglycemic agent',
    pharmacological: 'Pancreatic hormone',
    indications: ['Hypoglycemia', 'Beta blocker overdose', 'Calcium channel blocker overdose'],
    contraindications: ['Pheochromocytoma (tumor on the adrenal gland)', 'Insulinoma (tumor in the pancreas)'],
    cautions: [],
    adult: ['1–2 mg IM'],
    peds: ['Less than 20 kg: 0.5 mg IM/IV', 'Greater than 20 kg: 1 mg IM/IV'],
    moa: 'Breaks down glycogen to glucose and stimulates glucose synthesis; positive inotropic action on the heart; decreases renal vascular resistance.',
    adverse: ['Tachycardia', 'Hypotension', 'Nausea', 'Vomiting'],
    protocolsTN: ['Hypoglycemia', 'Beta blocker OD'],
    protocolsNASEMSO: ['Hypoglycemia', 'Beta blocker OD', 'Calcium channel blocker OD'],
    mnemonic: '',
    notes: ['Can be given IN.']
  },
  {
    id: 'ibuprofen',
    name: 'Ibuprofen',
    aliases: ['motrin', 'advil'],
    trade: ['Motrin', 'Advil'],
    groups: ['pain'],
    label: 'other',
    therapeutic: 'Analgesic; anti-inflammatory',
    pharmacological: 'NSAID',
    indications: ['Fever control', 'Mild pain relief'],
    contraindications: ['Aspirin allergy', 'GI bleed', 'Head bleed', 'Renal impairment'],
    cautions: [],
    adult: ['600 mg PO'],
    peds: ['>6 months: 10 mg/kg PO'],
    moa: 'Inhibits the synthesis of prostaglandins in body tissues.',
    adverse: ['Diarrhea', 'Constipation', 'Gas', 'Headache'],
    protocolsTN: ['Fever control'],
    protocolsNASEMSO: ['Mild pain management', 'Febrile seizures', 'Altitude sickness', 'Shock'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'lidocaine',
    name: 'Lidocaine 2%',
    aliases: ['lidocaine', 'lido', 'xylocaine', 'lidopen'],
    trade: ['Xylocaine', 'LidoPen'],
    groups: ['cardiac'],
    label: 'local',
    therapeutic: 'Class 1b antidysrhythmic',
    pharmacological: 'Sodium channel blocker',
    indications: ['Ventricular dysrhythmias', 'Malignant PVCs', 'Post-conversion of V-fib / V-tach'],
    contraindications: ['Second and third degree block', 'WPW', 'Bradycardia', 'Junctional and idioventricular rhythms (do not follow the SA node pathway)'],
    cautions: [],
    adult: ['IO procedure: 20–50 mg', '1–1.5 mg/kg IVP (max 3 mg/kg)', 'Drip: 2–4 mg/min'],
    peds: ['0.5–1 mg/kg', 'Drip: 20–50 mcg/min'],
    moa: 'Increases V-fib threshold; decreases automaticity and dromotropic effect.',
    adverse: ['Bradycardia', 'Hypotension', 'Headache', 'Dizziness'],
    protocolsTN: ['Ventricular fibrillation / pulseless V-tach', 'IO procedure'],
    protocolsNASEMSO: ['IO procedure', 'Regular wide complex tachycardia (stable)', 'Cardiac arrest VF/VT'],
    mnemonic: 'Lidocaine: LIGHTens up pain and calms ventricular arrhythmias.',
    notes: ['Drip: 2 g in 500 mL D5W = 4 mg/mL (always use a 60 gtt set).', '1 mg/min = 15 gtt/min · 2 mg/min = 30 gtt/min · 3 mg/min = 45 gtt/min · 4 mg/min = 60 gtt/min']
  },
  {
    id: 'magnesium',
    name: 'Magnesium Sulfate',
    aliases: ['magnesium', 'mag', 'mag sulfate', 'mgso4'],
    trade: [],
    groups: ['cardiac', 'resp'],
    label: 'other',
    therapeutic: 'Electrolyte; anticonvulsant; antidysrhythmic',
    pharmacological: 'Helps with sodium, calcium, and potassium movement',
    indications: ['Torsade de pointes', 'Severe bronchoconstriction', 'Seizure during pregnancy or postpartum'],
    contraindications: ['Shock', 'Heart blocks', 'Hypermagnesemia', 'Myasthenia gravis'],
    cautions: [],
    adult: ['Torsade de pointes: 1–2 g', 'Pregnancy: 2–4 g', 'Drip: 4 g / 250 mL run at 30–60 gtt/min'],
    peds: ['VF/VT: 50 mg/kg IV', 'Torsade: 50 mg/kg (max 2 g)'],
    moa: 'Depresses the CNS; blocks peripheral neuromuscular transmission; slows SA node impulse.',
    adverse: ['Nausea', 'Cramps', 'Bradycardia', 'Hypocalcemia', 'Decreased tendon reflexes', 'Hypotension'],
    protocolsTN: ["Torsade de pointes", 'Ventricular asystole', 'V-fib / V-tach', 'Respiratory distress (asthma/COPD)', 'Preeclampsia and eclampsia'],
    protocolsNASEMSO: ["Torsade de pointes", 'Seizure in pregnancy', 'Severe respiratory distress'],
    mnemonic: 'Magnesium: Mega muscle relaxer. 1 g per lung; increased dose for pregnancy.',
    notes: []
  },
  {
    id: 'methylprednisolone',
    name: 'Methylprednisolone',
    aliases: ['solu-medrol', 'solumedrol', 'solu medrol'],
    trade: ['Solu-Medrol'],
    groups: ['resp'],
    label: 'other',
    therapeutic: 'Corticosteroid',
    pharmacological: 'Anti-inflammatory',
    indications: ['Acute bronchospastic disease'],
    contraindications: ['Untreated infections'],
    cautions: [],
    adult: ['125 mg IV', '62.5 mg (small stature, chronic steroid use)'],
    peds: ['Contact medical control'],
    moa: 'Suppresses the immune response by binding intracellular corticosteroid receptors, decreasing inflammation.',
    adverse: ['Hypertension', 'Headache', 'CNS depression'],
    protocolsTN: ['Respiratory distress'],
    protocolsNASEMSO: ['Shock', 'Respiratory distress'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'midazolam',
    name: 'Midazolam',
    aliases: ['versed'],
    trade: ['Versed'],
    groups: ['pain'],
    label: 'benzo',
    therapeutic: 'Benzodiazepine',
    pharmacological: 'Anticonvulsant',
    indications: ['Sedation', 'Seizure'],
    contraindications: ['Hypotension', 'Shock', 'Head injury'],
    cautions: [],
    adult: ['2–5 mg IV or IM'],
    peds: ['0.1 mg/kg'],
    moa: 'Suppresses seizure activity; produces amnesia and relaxes skeletal muscle.',
    adverse: ['Hypotension', 'Respiratory depression', 'Drowsiness', 'Apnea'],
    protocolsTN: ['Sedation prior to cardioversion', 'Seizures', 'Snake bite', 'Combative patient', 'Chemical restraint'],
    protocolsNASEMSO: ['Combative patient', 'End of life care', 'Seizures', 'Temperature control', 'Calcium channel blocker OD'],
    mnemonic: '',
    notes: ['Can be given IN.', 'Use flumazenil (Romazicon) to treat OD.']
  },
  {
    id: 'morphine',
    name: 'Morphine Sulfate',
    aliases: ['morphine', 'ms contin', 'duramorph', 'ms'],
    trade: ['MS Contin', 'Duramorph'],
    groups: ['pain'],
    label: 'opioid',
    therapeutic: 'Analgesic',
    pharmacological: 'Opioid analgesic',
    indications: ['Pain', 'Sedation'],
    contraindications: ['Head injury', 'Altered level of consciousness', 'Hypovolemia'],
    cautions: [],
    adult: ['2–4 mg'],
    peds: ['0.1–0.2 mg/kg'],
    moa: 'Binds to opioid receptors to produce analgesia, sedation, and euphoria; reduces preload and afterload.',
    adverse: ['Nausea', 'Vomiting', 'Hypotension', 'Sedation', 'Respiratory depression', 'Bradycardia'],
    protocolsTN: ['Pain management (second line)'],
    protocolsNASEMSO: ['Chest pain', 'End of life care', 'Pain management'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'naloxone',
    name: 'Naloxone',
    aliases: ['narcan'],
    trade: ['Narcan'],
    groups: ['tox'],
    label: 'antagonist',
    therapeutic: 'Narcotic antagonist',
    pharmacological: 'Antidote',
    indications: ['Opioid overdose'],
    contraindications: ['Hypersensitivity'],
    cautions: [],
    adult: ['0.4–2 mg slow IVP (max 8 mg)'],
    peds: ['0.1 mg/kg slow IVP'],
    moa: 'Blocks the opioid receptor sites.',
    adverse: ['Vomiting', 'Nausea', 'Withdrawal'],
    protocolsTN: ['Unresponsive', 'Opioid OD'],
    protocolsNASEMSO: ['Unresponsive', 'Opioid OD'],
    mnemonic: '',
    notes: ['Goal: restore respiratory effort.']
  },
  {
    id: 'nitroglycerin',
    name: 'Nitroglycerin',
    aliases: ['nitro', 'ntg', 'nitroglycerine', 'nitrostat', 'nitro-bid', 'nitro bid'],
    trade: ['Nitrostat', 'Nitro-Bid'],
    groups: ['cardiac'],
    label: 'other',
    therapeutic: 'Vasodilator',
    pharmacological: 'Nitrate',
    indications: ['Chest pain', 'Pulmonary edema'],
    contraindications: ['Hypotension', 'Cerebral hemorrhage or head injury', 'SED (sexual enhancement drug) use', 'Inferior AMI (relative)'],
    cautions: ['Alcohol use'],
    adult: ['0.4 mg SL (max dose 1.2 mg)', '1 inch transdermal', '10 mcg/min drip'],
    peds: ['N/A'],
    moa: 'Smooth muscle relaxer; decreases preload, afterload, and myocardial oxygen demand.',
    adverse: ['Hypotension', 'Headache', 'Bradycardia', 'Dizziness', 'Nausea'],
    protocolsTN: ['Acute coronary syndrome / STEMI', 'Chest pain / non-cardiac', 'Acute pulmonary edema / CHF', 'Hypertensive crisis'],
    protocolsNASEMSO: ['Chest pain / STEMI', 'Respiratory distress'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'nitrous-oxide',
    name: 'Nitrous Oxide',
    aliases: ['n2o', 'nitronox', 'nitrous'],
    trade: ['Nitronox'],
    groups: ['pain'],
    label: 'other',
    therapeutic: 'Inhalational anesthetic',
    pharmacological: 'CNS depressant',
    indications: ['Pain'],
    contraindications: ['Inability to follow commands', 'Altered LOC', 'Head injury', 'ETOH or drug use', 'Respiratory problems'],
    cautions: [],
    adult: ['Self-administered'],
    peds: ['Self-administered'],
    moa: 'Gas that produces anesthesia; relaxes coronary arteries and dilates smooth muscle.',
    adverse: ['Dizziness', 'Nausea', 'Decreased LOC', 'Respiratory depression'],
    protocolsTN: ['Musculoskeletal trauma'],
    protocolsNASEMSO: ['Pain management'],
    mnemonic: '',
    notes: ['Works similarly to benzodiazepines.', 'Can be abused.']
  },
  {
    id: 'ondansetron',
    name: 'Ondansetron',
    aliases: ['zofran'],
    trade: ['Zofran'],
    groups: ['tox'],
    label: 'antiemetic',
    therapeutic: 'Antiemetic',
    pharmacological: 'Serotonin receptor antagonist',
    indications: ['Nausea and vomiting'],
    contraindications: ['Widened QT interval', 'Serotonin syndrome (psych meds)'],
    cautions: ["Parkinson's disease"],
    adult: ['2–4 mg IV', '4–8 mg ODT'],
    peds: ['0.15 mg/kg IV'],
    moa: 'Blocks serotonin in the chemoreceptor trigger zone in the CNS and peripherally on vagal nerve terminals.',
    adverse: ['Prolonged QT interval'],
    protocolsTN: ['Nausea and vomiting', 'CPAP procedure', 'Opiate administration'],
    protocolsNASEMSO: ['Nausea and vomiting', 'Stimulant poisoning', 'Prophylactic with glucagon', 'Altitude sickness'],
    mnemonic: '',
    notes: []
  },
  {
    id: 'sodium-bicarbonate',
    name: 'Sodium Bicarbonate',
    aliases: ['bicarb', 'sodium bicarb', 'nahco3', 'bicarbonate'],
    trade: ['Bicarb'],
    concentration: '8.4% (4.2% for neonates)',
    groups: ['tox'],
    label: 'other',
    therapeutic: 'Antidote; electrolyte',
    pharmacological: 'Alkalizing agent',
    indications: ['Prolonged cardiac arrest', 'Hyperkalemia', 'Crush injuries', 'DKA', 'TCA, ASA, cocaine, or Benadryl overdose'],
    contraindications: ['Severe pulmonary edema', 'Alkalosis', 'Hypernatremia', 'Hypocalcemia'],
    cautions: ['Do not mix with calcium'],
    adult: ['1 mEq/kg IV, followed by 0.5 mEq/kg q10 min'],
    peds: ['<1 month: 1 mEq/kg IV (4.2%)'],
    moa: 'Binds hydrogen ions to form carbonic acid to restore pH.',
    adverse: ['Cramps', 'Alkalosis', 'Tetany', 'Twitching'],
    protocolsTN: ['SOP 105 PEA', 'Ventricular asystole', 'V-fib / V-tach', 'Agitated or combative patient', 'Chlorine exposure', 'Crush syndrome'],
    protocolsNASEMSO: ['Hyperglycemia', 'Cardiac arrest', 'TCA / sodium channel blocker overdose', 'Crush injury', 'Beta blocker overdose'],
    mnemonic: '',
    notes: ['DO NOT MIX WITH CALCIUM.']
  },
  {
    id: 'ketamine',
    name: 'Ketamine',
    aliases: ['ketalar'],
    trade: ['Ketalar'],
    groups: ['pain', 'rsi'],
    label: 'induction',
    therapeutic: 'Sedative; hypnotic; analgesic',
    pharmacological: 'Dissociative anesthetic',
    indications: ['Sedation', 'Pain management', 'Chemical restraint'],
    contraindications: ['Head injury'],
    cautions: ['Alcoholics'],
    adult: ['Pain: 0.1–0.3 mg/kg IV PRN (0.25–0.5 mg/kg IM/IN if no vascular access)', 'Agitation / sedation: 1.5–2 mg/kg IV slowly PRN', 'Agitation / sedation: 4 mg/kg IM (preferred initially in acutely agitated patient)', 'Airway (induction): 1–2 mg/kg IVP', 'Seizures not controlled by Versed: 1 mg/kg IV/IM'],
    peds: [],
    moa: 'Blocks the NMDA receptor of glutamate, the primary excitatory neurotransmitter in the brain.',
    adverse: ['Severe hallucinations', 'Tachycardia', 'Hypertension'],
    protocolsTN: ['Pain management (third line)', 'Post-intubation sedation', 'Sedation for cardioversion', 'Seizures', 'Crush injuries', 'Agitated and combative patient'],
    protocolsNASEMSO: ['Agitated patient', 'Pain management'],
    mnemonic: '',
    notes: ['Pain use: adjunct for musculoskeletal pain. Not for chest pain, headache, or penetrating eye trauma.', 'Induction agent of choice with suspected bronchospasm or asthma.', 'Sedation/analgesia agent of choice for NIPPV compliance because it maintains airway reflexes.', 'Adult doses come from the protocol screenshots in the deck. The deck lists no pediatric dose.']
  },
  {
    id: 'etomidate',
    name: 'Etomidate',
    aliases: ['amidate'],
    trade: ['Amidate'],
    groups: ['rsi'],
    label: 'induction',
    therapeutic: 'Hypnotic; anesthetic',
    pharmacological: 'Short-acting IV anesthetic',
    indications: ['Premedication for RSI', 'Cardioversion', 'Extrication'],
    contraindications: ['Labor and delivery', 'No analgesia', 'Septic shock'],
    cautions: [],
    adult: ['0.2–0.4 mg/kg'],
    peds: ['0.2–0.4 mg/kg'],
    moa: 'Imidazole compound that appears to depress CNS function via GABA.',
    adverse: ['Nausea and vomiting', 'Dysrhythmias', 'Hypotension', 'Hypertension', 'Cortisol suppression (septic shock)'],
    protocolsTN: [],
    protocolsNASEMSO: [],
    mnemonic: '',
    notes: []
  },
  {
    id: 'rocuronium',
    name: 'Rocuronium',
    aliases: ['roc', 'rocc', 'zemuron'],
    trade: ['Zemuron'],
    groups: ['rsi'],
    label: 'nmb',
    therapeutic: 'Paralytic',
    pharmacological: 'Nondepolarizing neuromuscular blocker',
    indications: ['Paralytic during RSI/DAI', 'Maintaining paralysis'],
    contraindications: ['Difficult airways', 'Chronic neuromuscular conditions such as myasthenia gravis'],
    cautions: [],
    adult: ['0.6–1.2 mg/kg IV'],
    peds: ['0.6–1.2 mg/kg IV (off-label use for RSI)'],
    moa: 'Blocks acetylcholine at the neuromuscular junction.',
    adverse: ['Apnea', 'Tachycardia', 'Hypertension'],
    protocolsTN: [],
    protocolsNASEMSO: [],
    mnemonic: '',
    notes: ['Duration 20–40 min.', 'DOES NOT PROVIDE ANALGESIA OR SEDATION.']
  },
  {
    id: 'succinylcholine',
    name: 'Succinylcholine',
    aliases: ['sux', 'succs', 'anectine'],
    trade: ['Anectine'],
    groups: ['rsi'],
    label: 'nmb',
    therapeutic: 'Paralytic',
    pharmacological: 'Depolarizing neuromuscular blocker',
    indications: ['Paralytic during RSI/DAI'],
    contraindications: ['Difficult airways', 'Burns or crush injuries greater than 72 hours old (potassium shift)', 'Skeletal muscle myopathies', 'Acute rhabdomyolysis', 'Chronic kidney disease', 'Malignant hyperthermia'],
    cautions: [],
    adult: ['1–1.5 mg/kg'],
    peds: ['Children: 1–1.5 mg/kg', 'Infants: 2 mg/kg (not as sensitive as adults)'],
    moa: 'Blocks acetylcholine at the neuromuscular junction.',
    adverse: ['Apnea', 'Tachycardia', 'Hypertension', 'Muscle fasciculation', 'Hyperkalemia'],
    protocolsTN: [],
    protocolsNASEMSO: [],
    mnemonic: '',
    notes: ['Duration of action 3–8 min.', 'DOES NOT PROVIDE ANALGESIA OR SEDATION.']
  },
  {
    id: 'vecuronium',
    name: 'Vecuronium',
    aliases: ['vec', 'norcuron'],
    trade: ['Norcuron'],
    groups: ['rsi'],
    label: 'nmb',
    therapeutic: 'Paralytic',
    pharmacological: 'Nondepolarizing neuromuscular blocker',
    indications: ['Paralytic during RSI/DAI', 'Maintaining paralysis'],
    contraindications: ['Difficult airways', 'Chronic neuromuscular conditions such as myasthenia gravis'],
    cautions: [],
    adult: ['0.1–0.2 mg/kg IV'],
    peds: ['0.1–0.3 mg/kg IV (off-label use for RSI)'],
    moa: 'Blocks acetylcholine at the neuromuscular junction.',
    adverse: ['Apnea', 'Tachycardia', 'Hypertension'],
    protocolsTN: [],
    protocolsNASEMSO: [],
    mnemonic: '',
    notes: ['Duration 40–60 min.', 'DOES NOT PROVIDE ANALGESIA OR SEDATION.']
  }
];

window.DRUG_GROUPS = [
  { id: 'cardiac', name: 'Cardiac' },
  { id: 'resp', name: 'Respiratory & allergy' },
  { id: 'pain', name: 'Pain, sedation & seizure' },
  { id: 'rsi', name: 'RSI' },
  { id: 'tox', name: 'Metabolic, antidotes & GI' }
];
